name: Bug Report
description: Report a bug or crash you encountered while playing with the mod.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please fill out all required fields so we can help you faster.
  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: What version of the mod are you using?
      placeholder: e.g., 1.2.3 for Minecraft 1.20.1
    validations:
      required: true
  - type: input
    id: forge_version
    attributes:
      label: Mod Loader & Version
      description: Which mod loader and version are you using?
      placeholder: e.g., Forge 47.1.0 / Fabric 0.15.10
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? What did you expect to happen instead?
      placeholder: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Start Minecraft
        2. Load into a world
        3. Perform the following...
        4. See the bug
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Crash Report / Logs
      description: Paste any crash report, latest.log, or relevant console output.
      render: shell
  - type: dropdown
    id: environment
    attributes:
      label: Operating System
      description: Which OS are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am using the latest version of the mod.
          required: true
        - label: I have checked that this issue isn’t already reported.
          required: true
