name: Feature Request
description: Suggest a new idea, feature, or improvement for the mod.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Got an idea to improve the mod? Let us know below!
  - type: input
    id: context
    attributes:
      label: Mod Version (Optional)
      description: If this feature is related to a specific version, mention it here.
      placeholder: e.g., 0.0.2
  - type: textarea
    id: feature_description
    attributes:
      label: Describe your idea
      description: Clearly explain the feature or change you’d like to see.
      placeholder: A clear and concise description of what you want.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why should this be added?
      description: What problem does it solve? What benefit does it bring?
      placeholder: Explain the motivation or use case.
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked that this feature hasn’t been suggested already.
          required: true
