plugins {
    id "java"
    id "com.gradleup.shadow" version "9.2.2"
}

group = project.maven_group
version = project.mod_version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(rootProject.java_version))
    withSourcesJar()
}

repositories {
    maven { url "https://repo.spongepowered.org/repository/maven-public/" }
    maven { url "https://maven.isxander.dev/releases" }
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    implementation "org.spongepowered:mixin:0.8.5"

    implementation 'io.github.projectaccounth:opengl-grl:0.1.8'
    implementation 'org.luaj:luaj-jse:3.0.1'
    
    compileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}"
}

tasks.withType(Jar) {
    zip64 = true
}
